version: "3.9"

services:
  app:
    image: silverbxlletz/reread:latest
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    depends_on:
      - db
    restart: always

  db:
    image: mongo:7
    restart: always
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: