version: "3.9"

services:
  app:
    build:
      context: .
      args:
        MONGODB_URI: ${MONGODB_URI}
        JWT_SECRET: ${JWT_SECRET}
    ports:
      - "3000:3000"
    env_file:
      - .env.local